### PR TITLE
Revert AGP to 7.3.1.

### PR DESCRIPTION
**Pull request by colinrtwhite**
[Intellij doesn't support AGP 7.4.0 yet](https://youtrack.jetbrains.com/issue/IDEA-280006/Improve-Android-plugin-merging-cadence).

### CODE REVIEW

**Comment by JakeWharton** [comment]
Jesse noted the lack of support in his PR to update yet still merged. I"ll defer to him.

**Comment by JakeWharton** [comment]
Actually that was in Okio https://github.com/square/okio/pull/1202

**Review by JakeWharton — APPROVED** [review]

**Comment by swankjesse** [comment]
Yeah, I think it’s worth prioritizing IntelliJ support 'cause it handles multiplatform better. Probably a mistake on my part with Okio.

**Comment by JakeWharton** [comment]
I'm not sure that's universally true (Redwood started that way but AS became better for it), but if we don't need 7.4 then there's no reason to jump up so fast either.

**Pull request merged**
