### PR TITLE
Rename the artifact for the native kotlin plugin

### PR DESCRIPTION
**Pull request by swankjesse**
Before: 'app.cash.zipline:hosted'
After: 'app.cash.zipline:zipline-kotlin-plugin-hosted'

### CODE REVIEW

**Review by JakeWharton — APPROVED** [review]

**Comment by swankjesse** [comment]
@JakeWharton please take another look. I don’t love it; I think it might be nicer to either change the name only for artifact publishing, or to move the `hosted` subdirectory to be top-level so I don’t need repetitive names when referring to it internally.

**Comment by JakeWharton** [comment]
Odd that you cannot change the name without also affecting the path. Perhaps time to switch to a properties file? https://github.com/cashapp/treehouse/blob/f1e8e409508bff5bf7b65dfe6fc2ffa541e43a68/treehouse/compose/compiler-hosted/gradle.properties#L1. It's how we divorce the project name from publish name everywhere else.

**Comment by swankjesse** [comment]
Yeah, that’s changing the artifact name and not the project name.

**Comment by swankjesse** [comment]
Alright, 3rd time’s a charm.

**Comment by swankjesse** [comment]
I dislike `gradle.properties` because it’s usually stringly-typed boilerplate. I prefer DRY gradle stuff and getting tools to yell at me if I mistype something.

**Pull request closed without merging**
