### PR TITLE
Workaround missing libtinfo.so.5 on Ubuntu

### PR DESCRIPTION
**Pull request by swankjesse**
We're getting this crash in our cklib builds:

    /home/runner/.cklib/clang-llvm-8.0.0-linux-x86-64/bin/clang: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory

StackOverflow suggests this might fix.

### CODE REVIEW

**Comment by swankjesse** [comment]
Related:
https://youtrack.jetbrains.com/issue/KT-42693/Remove-dependency-on-ncurses5-library

**Review by JakeWharton — APPROVED** [review]
This won't affect the ARM builds since they happen in the container, but maybe they're fine? Your error message seems to indicate x86_64 only but maybe there's other lines which were omitted.

**Comment by swankjesse** [comment]
Also related: https://github.com/touchlab/cklib/issues/8

**Comment by swankjesse** [comment]
I don’t think we do Linux + ARM, but it might be broken if we did.

**Comment by JakeWharton** [comment]
It's two steps up in these actions. Ubuntu runner + docker container for cross-compiliation.

**Pull request merged**
