### PR TITLE
Rename get/set to take/bind

### PR DESCRIPTION
**Pull request by veyndan**
You shouldn't be calling get or set multiple times.

### CODE REVIEW

**Comment by oldergod** [comment]
Can you call `put` 3 times and then do 3 `take` ?

**Comment by veyndan** [comment]
I'm assuming you mean with the same service name, so something like this would pass:

```kotlin
@Test fun multiPutAndTake(): Unit = runBlocking(dispatcher) {
  zipline.put<EchoService>("helloService", JvmEchoService("hi"))
  zipline.put<EchoService>("helloService", JvmEchoService("yo"))
  zipline.take<EchoService>("helloService")
  zipline.take<EchoService>("helloService")
}
```

But the reason for the name change is that we don't want to encourage this. You should be calling `close` on the service when it's no longer in use to prevent a resource leak. Having multiple `take`s encourages bad practice, so it's better to just store a reference to the service in a variable somewhere and then call `close` at some point.

**Comment by JakeWharton** [comment]
I told Jesse yesterday that put wasn't very strong here. What about register/consume?

**Comment by veyndan** [comment]
Yeah that sounds good. If we go with `register` though, presumably the better counterpart would be `unregister`. Thoughts?

**Comment by JakeWharton** [comment]
I'm okay with the terms being asymmetric because you never really unregister. Once you register we retain the claim on the name forever, even if you consume.

**Comment by veyndan** [comment]
@JakeWharton Updated the naming of things.

**Comment by JakeWharton** [comment]
@swankjesse Are you okay with this naming?

**Review by oldergod — APPROVED** [review]

**Review by JakeWharton — APPROVED** [review]

**Review by swankjesse — APPROVED** [review]
Thank you!

**Pull request merged**
